# Generated by Django 4.1.5 on 2023-01-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_alter_info_encoder_l_alter_info_encoder_r"),
    ]

    operations = [
        migrations.RemoveField(model_name="info", name="a",),
        migrations.AlterField(
            model_name="info",
            name="color_b",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="color_g",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="color_r",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
